### ISSUE TITLE
artilleryの実行結果のメモ

### ISSUE THREAD

**Issue by hideokamoto-stripe** [seike460/serverless-performance-handson#6]
```
--------------------------------
Summary report @ 23:50:10(+0000)
--------------------------------

http.codes.200: ................................................................ 2499
http.codes.502: ................................................................ 1101
http.downloaded_bytes: ......................................................... 52440083
http.request_rate: ............................................................. 59/sec
http.requests: ................................................................. 3600
http.response_time:
  min: ......................................................................... 206
  max: ......................................................................... 3402
  mean: ........................................................................ 1117.9
  median: ...................................................................... 1200.1
  p95: ......................................................................... 1720.2
  p99: ......................................................................... 2951.9
http.responses: ................................................................ 3600
vusers.completed: .............................................................. 3600
vusers.created: ................................................................ 3600
vusers.created_by_name.Get history: ............................................ 1797
vusers.created_by_name.Post to purchase: ....................................... 1803
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 218
  max: ......................................................................... 3907.3
  mean: ........................................................................ 1153.9
  median: ...................................................................... 1224.4
  p95: ......................................................................... 1720.2
  p99: ......................................................................... 2951.9
```
